name: finance_mate
description: A new Flutter project.

publish_to: 'none' # remove if publishing

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Tambahkan google_fonts di sini (level yang sama dengan flutter:)
  google_fonts: ^6.0.0

  # dependency lain kalau ada
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets (opsional)
  # assets:
  #   - assets/logo.png
